server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    # 数据库的用户名
    username: root
    # 数据库的密码
    password: liu021003
    type: com.alibaba.druid.pool.DruidDataSource